"""phase 3 forward capture tables

Revision ID: 34134455937d
Revises: c6e894509ff2
Create Date: 2026-08-01 10:00:59.526482

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = '34134455937d'
down_revision: str | None = 'c6e894509ff2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('canonical_game_id', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.String(length=8), nullable=False),
    sa.Column('player_id', sa.String(length=16), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('active_prob_low', sa.Float(), nullable=False),
    sa.Column('active_prob_high', sa.Float(), nullable=False),
    sa.Column('snap_share_low', sa.Float(), nullable=True),
    sa.Column('snap_share_high', sa.Float(), nullable=True),
    sa.Column('confidence_tier', sa.String(length=16), nullable=False),
    sa.Column('source_freshness_hours', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('missing_data', sa.Boolean(), nullable=False),
    sa.Column('is_starting_qb', sa.Boolean(), nullable=False),
    sa.Column('as_of_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_assessments_as_of_at'), 'availability_assessments', ['as_of_at'], unique=False)
    op.create_index(op.f('ix_availability_assessments_canonical_game_id'), 'availability_assessments', ['canonical_game_id'], unique=False)
    op.create_index(op.f('ix_availability_assessments_data_mode'), 'availability_assessments', ['data_mode'], unique=False)
    op.create_table('consensus_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('canonical_game_id', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('method_version', sa.String(length=32), nullable=False),
    sa.Column('median_line', sa.Float(), nullable=True),
    sa.Column('home_price_american', sa.Integer(), nullable=True),
    sa.Column('away_price_american', sa.Integer(), nullable=True),
    sa.Column('over_price_american', sa.Integer(), nullable=True),
    sa.Column('under_price_american', sa.Integer(), nullable=True),
    sa.Column('no_vig_home_prob', sa.Float(), nullable=True),
    sa.Column('no_vig_over_prob', sa.Float(), nullable=True),
    sa.Column('eligible_books', sa.Integer(), nullable=False),
    sa.Column('line_dispersion', sa.Float(), nullable=True),
    sa.Column('price_dispersion', sa.Float(), nullable=True),
    sa.Column('oldest_quote_age_seconds', sa.Integer(), nullable=True),
    sa.Column('newest_quote_age_seconds', sa.Integer(), nullable=True),
    sa.Column('quote_ids', sa.JSON(), nullable=False),
    sa.Column('is_closing_capture', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consensus_game_market_observed', 'consensus_snapshots', ['canonical_game_id', 'market', 'observed_at'], unique=False)
    op.create_index(op.f('ix_consensus_snapshots_canonical_game_id'), 'consensus_snapshots', ['canonical_game_id'], unique=False)
    op.create_index(op.f('ix_consensus_snapshots_data_mode'), 'consensus_snapshots', ['data_mode'], unique=False)
    op.create_index(op.f('ix_consensus_snapshots_observed_at'), 'consensus_snapshots', ['observed_at'], unique=False)
    op.create_table('forward_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('canonical_game_id', sa.String(length=32), nullable=False),
    sa.Column('forward_prediction_id', sa.String(length=120), nullable=True),
    sa.Column('policy_version', sa.String(length=48), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('horizon', sa.String(length=40), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('selection', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('qualifying_line', sa.Float(), nullable=True),
    sa.Column('qualifying_american', sa.Integer(), nullable=True),
    sa.Column('price_source', sa.String(length=32), nullable=True),
    sa.Column('price_age_seconds', sa.Integer(), nullable=True),
    sa.Column('model_probability', sa.Float(), nullable=True),
    sa.Column('conservative_probability', sa.Float(), nullable=True),
    sa.Column('break_even_probability', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('simulated_line', sa.Float(), nullable=True),
    sa.Column('simulated_american', sa.Integer(), nullable=True),
    sa.Column('simulated_delay_seconds', sa.Integer(), nullable=True),
    sa.Column('filled', sa.Boolean(), nullable=True),
    sa.Column('fill_note', sa.Text(), nullable=True),
    sa.Column('closing_line', sa.Float(), nullable=True),
    sa.Column('closing_american', sa.Integer(), nullable=True),
    sa.Column('closing_no_vig_prob', sa.Float(), nullable=True),
    sa.Column('clv_line', sa.Float(), nullable=True),
    sa.Column('clv_probability', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=12), nullable=True),
    sa.Column('pnl_units', sa.Float(), nullable=True),
    sa.Column('data_completeness', sa.Float(), nullable=True),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('as_of_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forward_ledger_canonical_game_id'), 'forward_ledger', ['canonical_game_id'], unique=False)
    op.create_index(op.f('ix_forward_ledger_data_mode'), 'forward_ledger', ['data_mode'], unique=False)
    op.create_index(op.f('ix_forward_ledger_policy_version'), 'forward_ledger', ['policy_version'], unique=False)
    op.create_index(op.f('ix_forward_ledger_status'), 'forward_ledger', ['status'], unique=False)
    op.create_table('forward_predictions',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('canonical_game_id', sa.String(length=32), nullable=False),
    sa.Column('horizon', sa.String(length=40), nullable=False),
    sa.Column('as_of_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('calibration_version', sa.String(length=64), nullable=True),
    sa.Column('feature_set_version', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.String(length=48), nullable=False),
    sa.Column('lineage', sa.JSON(), nullable=False),
    sa.Column('consensus_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('weather_vintage_id', sa.Integer(), nullable=True),
    sa.Column('availability_snapshot', sa.JSON(), nullable=True),
    sa.Column('expected_margin', sa.Float(), nullable=True),
    sa.Column('expected_total', sa.Float(), nullable=True),
    sa.Column('home_win_prob', sa.Float(), nullable=True),
    sa.Column('spread_cover_prob', sa.Float(), nullable=True),
    sa.Column('spread_push_prob', sa.Float(), nullable=True),
    sa.Column('total_over_prob', sa.Float(), nullable=True),
    sa.Column('total_push_prob', sa.Float(), nullable=True),
    sa.Column('margin_p10', sa.Float(), nullable=True),
    sa.Column('margin_p90', sa.Float(), nullable=True),
    sa.Column('total_p10', sa.Float(), nullable=True),
    sa.Column('total_p90', sa.Float(), nullable=True),
    sa.Column('data_completeness', sa.Float(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('artifact_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_game_id', 'horizon', 'model_version', 'policy_version', name='uq_forward_prediction_vintage')
    )
    op.create_index(op.f('ix_forward_predictions_as_of_at'), 'forward_predictions', ['as_of_at'], unique=False)
    op.create_index(op.f('ix_forward_predictions_canonical_game_id'), 'forward_predictions', ['canonical_game_id'], unique=False)
    op.create_index(op.f('ix_forward_predictions_data_mode'), 'forward_predictions', ['data_mode'], unique=False)
    op.create_index(op.f('ix_forward_predictions_horizon'), 'forward_predictions', ['horizon'], unique=False)
    op.create_index(op.f('ix_forward_predictions_policy_version'), 'forward_predictions', ['policy_version'], unique=False)
    op.create_table('forward_test_policies',
    sa.Column('policy_version', sa.String(length=48), nullable=False),
    sa.Column('policy_hash', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('feature_set_version', sa.String(length=32), nullable=False),
    sa.Column('calibration_version', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.Column('code_commit', sa.String(length=48), nullable=False),
    sa.Column('dependency_lock_hash', sa.String(length=64), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('policy_version')
    )
    op.create_table('injury_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('canonical_game_id', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.String(length=8), nullable=False),
    sa.Column('player_id', sa.String(length=16), nullable=False),
    sa.Column('report_date', sa.String(length=10), nullable=False),
    sa.Column('body_part', sa.String(length=48), nullable=True),
    sa.Column('practice_status', sa.String(length=24), nullable=True),
    sa.Column('game_designation', sa.String(length=24), nullable=True),
    sa.Column('source_category', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injury_observations_canonical_game_id'), 'injury_observations', ['canonical_game_id'], unique=False)
    op.create_index(op.f('ix_injury_observations_data_mode'), 'injury_observations', ['data_mode'], unique=False)
    op.create_index(op.f('ix_injury_observations_observed_at'), 'injury_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_injury_observations_source_category'), 'injury_observations', ['source_category'], unique=False)
    op.create_table('manual_book_price_entries',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('canonical_game_id', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('selection', sa.String(length=16), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('american', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.String(length=48), nullable=True),
    sa.Column('correction_of_id', sa.String(length=48), nullable=True),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_book_price_entries_canonical_game_id'), 'manual_book_price_entries', ['canonical_game_id'], unique=False)
    op.create_index(op.f('ix_manual_book_price_entries_data_mode'), 'manual_book_price_entries', ['data_mode'], unique=False)
    op.create_table('odds_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('canonical_game_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_event_id', sa.String(length=64), nullable=True),
    sa.Column('sportsbook', sa.String(length=48), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('selection', sa.String(length=16), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('american', sa.Integer(), nullable=False),
    sa.Column('decimal_odds', sa.Float(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('provider_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('raw_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_game_id', 'sportsbook', 'market', 'selection', 'line', 'american', 'provider_timestamp', name='uq_odds_quote_identity')
    )
    op.create_index('ix_odds_game_market_observed', 'odds_quotes', ['canonical_game_id', 'market', 'observed_at'], unique=False)
    op.create_index(op.f('ix_odds_quotes_canonical_game_id'), 'odds_quotes', ['canonical_game_id'], unique=False)
    op.create_index(op.f('ix_odds_quotes_data_mode'), 'odds_quotes', ['data_mode'], unique=False)
    op.create_index(op.f('ix_odds_quotes_observed_at'), 'odds_quotes', ['observed_at'], unique=False)
    op.create_table('provider_quota_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calls_used', sa.Integer(), nullable=False),
    sa.Column('calls_remaining', sa.Integer(), nullable=True),
    sa.Column('quota_limit', sa.Integer(), nullable=True),
    sa.Column('last_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_quota_usage_provider'), 'provider_quota_usage', ['provider'], unique=False)
    op.create_table('roof_state_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('canonical_game_id', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('source_category', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roof_state_observations_canonical_game_id'), 'roof_state_observations', ['canonical_game_id'], unique=False)
    op.create_index(op.f('ix_roof_state_observations_data_mode'), 'roof_state_observations', ['data_mode'], unique=False)
    op.create_index(op.f('ix_roof_state_observations_observed_at'), 'roof_state_observations', ['observed_at'], unique=False)
    op.create_table('schedule_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('canonical_game_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_game_id', sa.String(length=64), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.String(length=8), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.String(length=8), nullable=False),
    sa.Column('away_team_id', sa.String(length=8), nullable=False),
    sa.Column('kickoff_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue_timezone', sa.String(length=48), nullable=True),
    sa.Column('stadium_id', sa.String(length=24), nullable=True),
    sa.Column('stadium_name', sa.String(length=120), nullable=True),
    sa.Column('neutral_site', sa.Boolean(), nullable=False),
    sa.Column('international', sa.Boolean(), nullable=False),
    sa.Column('game_status', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_manifest_version', sa.String(length=64), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sched_obs_game_observed', 'schedule_observations', ['canonical_game_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_schedule_observations_canonical_game_id'), 'schedule_observations', ['canonical_game_id'], unique=False)
    op.create_index(op.f('ix_schedule_observations_data_mode'), 'schedule_observations', ['data_mode'], unique=False)
    op.create_index(op.f('ix_schedule_observations_observed_at'), 'schedule_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_schedule_observations_season'), 'schedule_observations', ['season'], unique=False)
    op.create_table('scheduled_job_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_kind', sa.String(length=48), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('provider_calls', sa.Integer(), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('code_commit', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_scheduled_job_runs_job_kind'), 'scheduled_job_runs', ['job_kind'], unique=False)
    op.create_table('venues',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=48), nullable=True),
    sa.Column('roof_type', sa.String(length=24), nullable=False),
    sa.Column('surface', sa.String(length=32), nullable=True),
    sa.Column('elevation_ft', sa.Float(), nullable=True),
    sa.Column('weather_applicable', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_forecast_vintages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('canonical_game_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('office', sa.String(length=8), nullable=True),
    sa.Column('grid_x', sa.Integer(), nullable=True),
    sa.Column('grid_y', sa.Integer(), nullable=True),
    sa.Column('forecast_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forecast_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temp_f', sa.Float(), nullable=True),
    sa.Column('wind_mph', sa.Float(), nullable=True),
    sa.Column('wind_gust_mph', sa.Float(), nullable=True),
    sa.Column('precip_probability', sa.Float(), nullable=True),
    sa.Column('precip_description', sa.String(length=120), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_artifact_path', sa.Text(), nullable=True),
    sa.Column('is_gameday_observation', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_forecast_vintages_canonical_game_id'), 'weather_forecast_vintages', ['canonical_game_id'], unique=False)
    op.create_index(op.f('ix_weather_forecast_vintages_data_mode'), 'weather_forecast_vintages', ['data_mode'], unique=False)
    op.create_index(op.f('ix_weather_forecast_vintages_observed_at'), 'weather_forecast_vintages', ['observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_forecast_vintages_observed_at'), table_name='weather_forecast_vintages')
    op.drop_index(op.f('ix_weather_forecast_vintages_data_mode'), table_name='weather_forecast_vintages')
    op.drop_index(op.f('ix_weather_forecast_vintages_canonical_game_id'), table_name='weather_forecast_vintages')
    op.drop_table('weather_forecast_vintages')
    op.drop_table('venues')
    op.drop_index(op.f('ix_scheduled_job_runs_job_kind'), table_name='scheduled_job_runs')
    op.drop_table('scheduled_job_runs')
    op.drop_index(op.f('ix_schedule_observations_season'), table_name='schedule_observations')
    op.drop_index(op.f('ix_schedule_observations_observed_at'), table_name='schedule_observations')
    op.drop_index(op.f('ix_schedule_observations_data_mode'), table_name='schedule_observations')
    op.drop_index(op.f('ix_schedule_observations_canonical_game_id'), table_name='schedule_observations')
    op.drop_index('ix_sched_obs_game_observed', table_name='schedule_observations')
    op.drop_table('schedule_observations')
    op.drop_index(op.f('ix_roof_state_observations_observed_at'), table_name='roof_state_observations')
    op.drop_index(op.f('ix_roof_state_observations_data_mode'), table_name='roof_state_observations')
    op.drop_index(op.f('ix_roof_state_observations_canonical_game_id'), table_name='roof_state_observations')
    op.drop_table('roof_state_observations')
    op.drop_index(op.f('ix_provider_quota_usage_provider'), table_name='provider_quota_usage')
    op.drop_table('provider_quota_usage')
    op.drop_index(op.f('ix_odds_quotes_observed_at'), table_name='odds_quotes')
    op.drop_index(op.f('ix_odds_quotes_data_mode'), table_name='odds_quotes')
    op.drop_index(op.f('ix_odds_quotes_canonical_game_id'), table_name='odds_quotes')
    op.drop_index('ix_odds_game_market_observed', table_name='odds_quotes')
    op.drop_table('odds_quotes')
    op.drop_index(op.f('ix_manual_book_price_entries_data_mode'), table_name='manual_book_price_entries')
    op.drop_index(op.f('ix_manual_book_price_entries_canonical_game_id'), table_name='manual_book_price_entries')
    op.drop_table('manual_book_price_entries')
    op.drop_index(op.f('ix_injury_observations_source_category'), table_name='injury_observations')
    op.drop_index(op.f('ix_injury_observations_observed_at'), table_name='injury_observations')
    op.drop_index(op.f('ix_injury_observations_data_mode'), table_name='injury_observations')
    op.drop_index(op.f('ix_injury_observations_canonical_game_id'), table_name='injury_observations')
    op.drop_table('injury_observations')
    op.drop_table('forward_test_policies')
    op.drop_index(op.f('ix_forward_predictions_policy_version'), table_name='forward_predictions')
    op.drop_index(op.f('ix_forward_predictions_horizon'), table_name='forward_predictions')
    op.drop_index(op.f('ix_forward_predictions_data_mode'), table_name='forward_predictions')
    op.drop_index(op.f('ix_forward_predictions_canonical_game_id'), table_name='forward_predictions')
    op.drop_index(op.f('ix_forward_predictions_as_of_at'), table_name='forward_predictions')
    op.drop_table('forward_predictions')
    op.drop_index(op.f('ix_forward_ledger_status'), table_name='forward_ledger')
    op.drop_index(op.f('ix_forward_ledger_policy_version'), table_name='forward_ledger')
    op.drop_index(op.f('ix_forward_ledger_data_mode'), table_name='forward_ledger')
    op.drop_index(op.f('ix_forward_ledger_canonical_game_id'), table_name='forward_ledger')
    op.drop_table('forward_ledger')
    op.drop_index(op.f('ix_consensus_snapshots_observed_at'), table_name='consensus_snapshots')
    op.drop_index(op.f('ix_consensus_snapshots_data_mode'), table_name='consensus_snapshots')
    op.drop_index(op.f('ix_consensus_snapshots_canonical_game_id'), table_name='consensus_snapshots')
    op.drop_index('ix_consensus_game_market_observed', table_name='consensus_snapshots')
    op.drop_table('consensus_snapshots')
    op.drop_index(op.f('ix_availability_assessments_data_mode'), table_name='availability_assessments')
    op.drop_index(op.f('ix_availability_assessments_canonical_game_id'), table_name='availability_assessments')
    op.drop_index(op.f('ix_availability_assessments_as_of_at'), table_name='availability_assessments')
    op.drop_table('availability_assessments')
    # ### end Alembic commands ###
