"""state origin and lineage constraints

Revision ID: abc511bec1a3
Revises: c034f7ebc265
Create Date: 2026-08-01 16:27:46.043259

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = 'abc511bec1a3'
down_revision: str | None = 'c034f7ebc265'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_job_runs', sa.Column('state_origin', sa.String(length=20), nullable=False, server_default='LIVE'))
    op.create_index('ix_run_root_slot', 'scheduled_job_runs', ['root_run_id', 'logical_slot'], unique=False)
    op.create_index(op.f('ix_scheduled_job_runs_state_origin'), 'scheduled_job_runs', ['state_origin'], unique=False)
    # ### end Alembic commands ###



    # Rows already carrying UNKNOWN_LEGACY came from the split migration, so
    # they are labelled MIGRATED_LEGACY before the CHECK constraint applies.
    op.get_bind().execute(
        sa.text("UPDATE scheduled_job_runs SET state_origin='MIGRATED_LEGACY' "
                "WHERE domain_state = 'UNKNOWN_LEGACY'")
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_job_runs_state_origin'), table_name='scheduled_job_runs')
    op.drop_index('ix_run_root_slot', table_name='scheduled_job_runs')
    op.drop_column('scheduled_job_runs', 'state_origin')
    # ### end Alembic commands ###
