"""scheduler outcome/domain split and recovery lineage

Revision ID: c034f7ebc265
Revises: 34134455937d
Create Date: 2026-08-01 15:41:28.016749

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import fde_api.db.models

revision: str = 'c034f7ebc265'
down_revision: str | None = '34134455937d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('revision', sa.String(length=48), nullable=False),
    sa.Column('migration_cycle', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.String(length=96), nullable=False),
    sa.Column('original_value', sa.String(length=48), nullable=True),
    sa.Column('new_outcome', sa.String(length=24), nullable=True),
    sa.Column('new_domain_state', sa.String(length=24), nullable=True),
    sa.Column('mapping_rule', sa.String(length=120), nullable=False),
    sa.Column('exact', sa.Boolean(), nullable=False),
    sa.Column('migrated_at', fde_api.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision', 'migration_cycle', 'table_name', 'record_id',
                        name='uq_migration_audit_identity')
    )
    op.create_index(op.f('ix_migration_audit_revision'), 'migration_audit', ['revision'], unique=False)
    op.add_column('scheduled_job_runs', sa.Column('job_outcome', sa.String(length=24), nullable=True))
    op.add_column('scheduled_job_runs', sa.Column('domain_state', sa.String(length=24), nullable=True))
    op.add_column('scheduled_job_runs', sa.Column('root_run_id', sa.String(length=64), nullable=True))
    op.add_column('scheduled_job_runs', sa.Column('recovery_of_run_id', sa.String(length=64), nullable=True))
    op.add_column('scheduled_job_runs',
                  sa.Column('recovery_sequence', sa.Integer(), nullable=False,
                            server_default='0'))
    op.add_column('scheduled_job_runs', sa.Column('logical_slot', fde_api.db.models.UtcDateTime(timezone=True), nullable=True))
    op.add_column('scheduled_job_runs', sa.Column('original_idempotency_key', sa.String(length=160), nullable=True))
    op.add_column('scheduled_job_runs', sa.Column('recovery_reason', sa.Text(), nullable=True))
    op.add_column('scheduled_job_runs', sa.Column('reconciled_at', fde_api.db.models.UtcDateTime(timezone=True), nullable=True))
    op.add_column('scheduled_job_runs', sa.Column('prior_effects_detected', sa.Boolean(), nullable=True))
    op.add_column('scheduled_job_runs', sa.Column('replay_decision', sa.String(length=40), nullable=True))
    op.add_column('scheduled_job_runs',
                  sa.Column('administrative_override', sa.Boolean(), nullable=False,
                            server_default=sa.false()))
    op.add_column('scheduled_job_runs', sa.Column('override_operator', sa.String(length=80), nullable=True))
    op.add_column('scheduled_job_runs', sa.Column('override_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_scheduled_job_runs_domain_state'), 'scheduled_job_runs', ['domain_state'], unique=False)
    op.create_index(op.f('ix_scheduled_job_runs_job_outcome'), 'scheduled_job_runs', ['job_outcome'], unique=False)
    op.create_index(op.f('ix_scheduled_job_runs_root_run_id'), 'scheduled_job_runs', ['root_run_id'], unique=False)
    # ### end Alembic commands ###



    # ------------------------------------------------------------------ #
    # Data migration: split the legacy single-state column into the two
    # independent axes, recording every reinterpretation in migration_audit.
    #
    # Nothing here infers a stronger state than the stored data supports.
    # Where the legacy value cannot determine the domain state, the mapping
    # is marked conservative and the original value is preserved in `status`.
    # ------------------------------------------------------------------ #
    _split_legacy_scheduler_state()


# Deterministic mapping from every legacy value to (outcome, domain_state,
# rule_name, exact). `exact` is False when the domain state is a conservative
# default rather than something the legacy row actually recorded.
LEGACY_STATE_MAP: dict[str, tuple[str, str, str, bool]] = {
    # Legacy execution status establishes the OUTCOME exactly. It does NOT
    # establish the domain state: "finished" means the job ran, not that the
    # data was complete. Domain state is exact only when preserved metadata
    # records it explicitly (applied separately below).
    "finished": ("SUCCESS", "UNKNOWN_LEGACY",
                 "finished->SUCCESS; domain not recorded (conservative)", False),
    "running": ("RUNNING", "UNKNOWN_LEGACY",
                "running->RUNNING; domain not recorded (conservative)", False),
    "queued": ("RUNNING", "UNKNOWN_LEGACY",
               "queued->RUNNING; domain not recorded (conservative)", False),
    "failed": ("RETRYABLE_FAILURE", "UNKNOWN_LEGACY",
               "failed->RETRYABLE_FAILURE; domain not recorded (conservative)", False),
    "dead_letter": ("TERMINAL_FAILURE", "UNKNOWN_LEGACY",
                    "dead_letter->TERMINAL_FAILURE; domain not recorded (conservative)", False),
    "interrupted": ("INTERRUPTED", "UNKNOWN_LEGACY",
                    "interrupted->INTERRUPTED; domain not recorded (conservative)", False),
    "skipped": ("SKIPPED", "UNKNOWN_LEGACY",
                "skipped->SKIPPED; domain not recorded (conservative)", False),
    # Outcome-style legacy values, if any row carried them.
    "SUCCESS": ("SUCCESS", "UNKNOWN_LEGACY",
                "SUCCESS->SUCCESS; domain not recorded (conservative)", False),
    "SUCCESS_WITH_WARNINGS": ("SUCCESS_WITH_WARNINGS", "UNKNOWN_LEGACY",
                              "SUCCESS_WITH_WARNINGS; domain not recorded (conservative)", False),
    "SKIPPED": ("SKIPPED", "UNKNOWN_LEGACY",
                "SKIPPED; domain not recorded (conservative)", False),
    "RETRYABLE_FAILURE": ("RETRYABLE_FAILURE", "UNKNOWN_LEGACY",
                          "RETRYABLE_FAILURE; domain not recorded (conservative)", False),
    "TERMINAL_FAILURE": ("TERMINAL_FAILURE", "UNKNOWN_LEGACY",
                         "TERMINAL_FAILURE; domain not recorded (conservative)", False),
    "INTERRUPTED": ("INTERRUPTED", "UNKNOWN_LEGACY",
                    "INTERRUPTED; domain not recorded (conservative)", False),
    # These two legacy values WERE domain states misfiled as outcomes, so the
    # domain reconstruction is exact.
    "DATA_INCOMPLETE": ("SUCCESS_WITH_WARNINGS", "DATA_INCOMPLETE",
                        "legacy DATA_INCOMPLETE was a domain state, not an outcome", True),
    "SUPPRESSED": ("SUCCESS_WITH_WARNINGS", "SUPPRESSED",
                   "legacy SUPPRESSED was a domain state, not an outcome", True),
}


# Domain states recoverable from the preserved error_summary text, which is
# where the split briefly lived before it became a column.
_METADATA_STATES = (
    "SUPPRESSED", "DATA_INCOMPLETE", "NOT_YET_AVAILABLE",
    "NOT_APPLICABLE", "STALE", "NO_ELIGIBLE_RECORDS", "COMPLETE",
)


def _split_legacy_scheduler_state() -> None:
    from datetime import UTC, datetime

    conn = op.get_bind()
    rows = conn.execute(
        sa.text("SELECT id, status, error_summary, idempotency_key, scheduled_for "
                "FROM scheduled_job_runs")
    ).fetchall()
    now = datetime.now(tz=UTC)

    # A downgrade removes this revision's audit rows, so a re-upgrade starts a
    # NEW cycle. Cycle number makes repeated applications distinguishable
    # rather than silently duplicated.
    prior = conn.execute(
        sa.text("SELECT COALESCE(MAX(migration_cycle), 0) FROM migration_audit "
                "WHERE revision = :r"),
        {"r": revision},
    ).scalar() or 0
    cycle = int(prior) + 1

    for row in rows:
        run_id, legacy, summary, idem_key, slot = row[0], row[1], row[2], row[3], row[4]
        outcome, domain, rule, exact = LEGACY_STATE_MAP.get(
            legacy, ("SUCCESS_WITH_WARNINGS", "DATA_INCOMPLETE",
                     f"unrecognized legacy value {legacy!r}; conservative default", False)
        )
        # Prefer a domain state the row actually recorded over the default.
        if summary:
            for candidate in _METADATA_STATES:
                if f"domain_state={candidate}" in summary:
                    domain, rule, exact = candidate, f"{rule}; refined from recorded metadata", True
                    break

        conn.execute(
            sa.text(
                "UPDATE scheduled_job_runs SET job_outcome=:o, domain_state=:d, "
                "root_run_id=COALESCE(root_run_id, :rid), recovery_sequence=0, "
                "logical_slot=COALESCE(logical_slot, :slot), "
                "original_idempotency_key=COALESCE(original_idempotency_key, :ik), "
                "administrative_override=0 WHERE id=:rid2"
            ),
            {"o": outcome, "d": domain, "rid": run_id, "slot": slot,
             "ik": idem_key, "rid2": run_id},
        )
        conn.execute(
            sa.text(
                "INSERT INTO migration_audit (revision, migration_cycle, table_name, "
                "record_id, original_value, new_outcome, new_domain_state, mapping_rule, "
                "exact, migrated_at) "
                "VALUES (:rev, :cycle, :tbl, :rec, :orig, :o, :d, :rule, :exact, :ts)"
            ),
            {"rev": revision, "cycle": cycle, "tbl": "scheduled_job_runs",
             "rec": str(run_id), "orig": legacy, "o": outcome, "d": domain,
             "rule": rule, "exact": 1 if exact else 0, "ts": now},
        )


def downgrade() -> None:
    """Downgrade is supported and lossless for the legacy representation.

    The legacy `status` column was never dropped, so removing the new
    columns returns the table to its prior shape. The migration_audit rows
    for this revision are removed with it.
    """
    op.get_bind().execute(
        sa.text("DELETE FROM migration_audit WHERE revision = :r"), {"r": revision}
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_job_runs_root_run_id'), table_name='scheduled_job_runs')
    op.drop_index(op.f('ix_scheduled_job_runs_job_outcome'), table_name='scheduled_job_runs')
    op.drop_index(op.f('ix_scheduled_job_runs_domain_state'), table_name='scheduled_job_runs')
    op.drop_column('scheduled_job_runs', 'override_reason')
    op.drop_column('scheduled_job_runs', 'override_operator')
    op.drop_column('scheduled_job_runs', 'administrative_override')
    op.drop_column('scheduled_job_runs', 'replay_decision')
    op.drop_column('scheduled_job_runs', 'prior_effects_detected')
    op.drop_column('scheduled_job_runs', 'reconciled_at')
    op.drop_column('scheduled_job_runs', 'recovery_reason')
    op.drop_column('scheduled_job_runs', 'original_idempotency_key')
    op.drop_column('scheduled_job_runs', 'logical_slot')
    op.drop_column('scheduled_job_runs', 'recovery_sequence')
    op.drop_column('scheduled_job_runs', 'recovery_of_run_id')
    op.drop_column('scheduled_job_runs', 'root_run_id')
    op.drop_column('scheduled_job_runs', 'domain_state')
    op.drop_column('scheduled_job_runs', 'job_outcome')
    op.drop_index(op.f('ix_migration_audit_revision'), table_name='migration_audit')
    op.drop_table('migration_audit')
    # ### end Alembic commands ###
