"""initial canonical schema

Revision ID: c6e894509ff2
Revises:
Create Date: 2026-08-01 07:50:48.883845

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = 'c6e894509ff2'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calibration_artifacts',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('target', sa.String(length=48), nullable=False),
    sa.Column('fitted_on', sa.String(length=64), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_quality_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('scope', sa.String(length=48), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_runs',
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('dataset', sa.String(length=48), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.String(length=48), nullable=False),
    sa.Column('code_commit', sa.String(length=48), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source_version', sa.String(length=128), nullable=True),
    sa.Column('source_updated_at', sa.String(length=48), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('target', sa.String(length=48), nullable=False),
    sa.Column('algorithm', sa.String(length=80), nullable=False),
    sa.Column('train_window', sa.String(length=48), nullable=True),
    sa.Column('validation_window', sa.String(length=48), nullable=True),
    sa.Column('test_window', sa.String(length=48), nullable=True),
    sa.Column('feature_set', sa.String(length=32), nullable=True),
    sa.Column('calibration_version', sa.String(length=64), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('dataset_hashes', sa.JSON(), nullable=False),
    sa.Column('artifact_hash', sa.String(length=64), nullable=True),
    sa.Column('code_commit', sa.String(length=48), nullable=False),
    sa.Column('dependency_lock_hash', sa.String(length=64), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('known_limitations', sa.Text(), nullable=False),
    sa.Column('approval_status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('officials',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('birth_date', sa.String(length=10), nullable=True),
    sa.Column('first_season', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_entity_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=24), nullable=False),
    sa.Column('provider_id', sa.String(length=80), nullable=False),
    sa.Column('canonical_id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'entity_type', 'provider_id')
    )
    op.create_table('stadiums',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('roof', sa.String(length=16), nullable=True),
    sa.Column('surface', sa.String(length=32), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('conference', sa.String(length=8), nullable=True),
    sa.Column('division', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=8), nullable=False),
    sa.Column('kickoff_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_team_id', sa.String(length=8), nullable=False),
    sa.Column('away_team_id', sa.String(length=8), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('overtime', sa.Boolean(), nullable=True),
    sa.Column('stadium_id', sa.String(length=16), nullable=True),
    sa.Column('roof', sa.String(length=16), nullable=True),
    sa.Column('surface', sa.String(length=32), nullable=True),
    sa.Column('temp_f', sa.Float(), nullable=True),
    sa.Column('wind_mph', sa.Float(), nullable=True),
    sa.Column('referee_id', sa.String(length=80), nullable=True),
    sa.Column('home_rest_days', sa.Integer(), nullable=True),
    sa.Column('away_rest_days', sa.Integer(), nullable=True),
    sa.Column('div_game', sa.Boolean(), nullable=True),
    sa.Column('home_qb_id', sa.String(length=16), nullable=True),
    sa.Column('away_qb_id', sa.String(length=16), nullable=True),
    sa.Column('home_coach', sa.String(length=80), nullable=True),
    sa.Column('away_coach', sa.String(length=80), nullable=True),
    sa.Column('result_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_manifest_version', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['officials.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.create_index('ix_games_season_week', 'games', ['season', 'week'], unique=False)
    op.create_table('injury_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=8), nullable=False),
    sa.Column('player_id', sa.String(length=16), nullable=False),
    sa.Column('practice_status', sa.String(length=32), nullable=True),
    sa.Column('game_status', sa.String(length=32), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_evaluations',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('model_version_id', sa.String(length=80), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_evaluations_model_version_id'), 'model_evaluations', ['model_version_id'], unique=False)
    op.create_table('roster_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=8), nullable=False),
    sa.Column('player_id', sa.String(length=16), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('depth_chart_order', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'team_id', 'player_id')
    )
    op.create_index(op.f('ix_roster_entries_season'), 'roster_entries', ['season'], unique=False)
    op.create_table('backtest_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backtest_run_id', sa.String(length=64), nullable=False),
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('prediction_id', sa.String(length=96), nullable=True),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('selection', sa.String(length=8), nullable=True),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('price_american', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('execution', sa.JSON(), nullable=True),
    sa.Column('settlement', sa.JSON(), nullable=True),
    sa.Column('as_of_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_recommendations_backtest_run_id'), 'backtest_recommendations', ['backtest_run_id'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('feature_set', sa.String(length=32), nullable=False),
    sa.Column('horizon', sa.String(length=24), nullable=False),
    sa.Column('as_of_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('unavailable_features', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('code_commit', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'feature_set', 'horizon', 'as_of_at')
    )
    op.create_index(op.f('ix_feature_snapshots_game_id'), 'feature_snapshots', ['game_id'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('book', sa.String(length=48), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('home_price_american', sa.Integer(), nullable=True),
    sa.Column('away_price_american', sa.Integer(), nullable=True),
    sa.Column('over_price_american', sa.Integer(), nullable=True),
    sa.Column('under_price_american', sa.Integer(), nullable=True),
    sa.Column('snapshot_kind', sa.String(length=24), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_manifest_version', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_odds_game_market', 'odds_snapshots', ['game_id', 'market'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_game_id'), 'odds_snapshots', ['game_id'], unique=False)
    op.create_table('participation_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('player_id', sa.String(length=16), nullable=False),
    sa.Column('team_id', sa.String(length=8), nullable=False),
    sa.Column('snap_share', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id')
    )
    op.create_table('team_game_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('team_id', sa.String(length=8), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_id')
    )
    op.create_index(op.f('ix_team_game_stats_game_id'), 'team_game_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_team_game_stats_season'), 'team_game_stats', ['season'], unique=False)
    op.create_table('weather_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('temp_f', sa.Float(), nullable=True),
    sa.Column('wind_mph', sa.Float(), nullable=True),
    sa.Column('wind_gust_mph', sa.Float(), nullable=True),
    sa.Column('precip_prob', sa.Float(), nullable=True),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('model_version_id', sa.String(length=80), nullable=False),
    sa.Column('feature_snapshot_id', sa.String(length=80), nullable=True),
    sa.Column('horizon', sa.String(length=24), nullable=False),
    sa.Column('as_of_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['feature_snapshots.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'model_version_id', 'horizon', 'as_of_at')
    )
    op.create_index(op.f('ix_predictions_game_id'), 'predictions', ['game_id'], unique=False)
    op.create_table('prediction_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_components_prediction_id'), 'prediction_components', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_components_prediction_id'), table_name='prediction_components')
    op.drop_table('prediction_components')
    op.drop_index(op.f('ix_predictions_game_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('weather_snapshots')
    op.drop_index(op.f('ix_team_game_stats_season'), table_name='team_game_stats')
    op.drop_index(op.f('ix_team_game_stats_game_id'), table_name='team_game_stats')
    op.drop_table('team_game_stats')
    op.drop_table('participation_records')
    op.drop_index(op.f('ix_odds_snapshots_game_id'), table_name='odds_snapshots')
    op.drop_index('ix_odds_game_market', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index(op.f('ix_feature_snapshots_game_id'), table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_index(op.f('ix_backtest_recommendations_backtest_run_id'), table_name='backtest_recommendations')
    op.drop_table('backtest_recommendations')
    op.drop_index(op.f('ix_roster_entries_season'), table_name='roster_entries')
    op.drop_table('roster_entries')
    op.drop_index(op.f('ix_model_evaluations_model_version_id'), table_name='model_evaluations')
    op.drop_table('model_evaluations')
    op.drop_table('injury_reports')
    op.drop_index('ix_games_season_week', table_name='games')
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('stadiums')
    op.drop_table('provider_entity_map')
    op.drop_table('players')
    op.drop_table('officials')
    op.drop_table('model_versions')
    op.drop_table('jobs')
    op.drop_table('ingestion_runs')
    op.drop_table('data_quality_events')
    op.drop_table('calibration_artifacts')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
